import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Card, CardContent } from './ui';
import { currency, titleCase } from '../lib/utils';
const colors = ['#0f9f92', '#3b82f6', '#8b5cf6', '#f59e0b', '#ef4444', '#64748b'];
const tipStyle = { background: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: 8 };
export function ChartCard({ title, subtitle, children }) { return <Card><CardContent><h3 className="font-semibold">{title}</h3>{subtitle && <p className="mb-4 text-xs text-muted-foreground">{subtitle}</p>}<div className="mt-4 h-72">{children}</div></CardContent></Card>; }
export function TrendChart({ data = [], dataKey = 'bookings', currencyValues = false }) { return <ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={0.25} /><XAxis dataKey="date" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} tickFormatter={currencyValues ? (v) => `₹${Math.round(v / 1000)}k` : undefined} /><Tooltip contentStyle={tipStyle} formatter={currencyValues ? (v) => currency(v) : undefined} /><Line type="monotone" dataKey={dataKey} stroke="#0f9f92" strokeWidth={2.5} dot={false} /></LineChart></ResponsiveContainer>; }
export function StatusPie({ data = [] }) { return <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="count" nameKey="status" innerRadius={58} outerRadius={92} paddingAngle={3}>{data.map((_, index) => <Cell key={index} fill={colors[index % colors.length]} />)}</Pie><Tooltip contentStyle={tipStyle} formatter={(v, n) => [v, titleCase(n)]} /><Legend formatter={titleCase} /></PieChart></ResponsiveContainer>; }
export function ServiceBars({ data = [] }) { return <ResponsiveContainer width="100%" height="100%"><BarChart data={data.slice(0, 8)} layout="vertical" margin={{ left: 15 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} opacity={0.25} /><XAxis type="number" /><YAxis type="category" dataKey="service" width={100} tick={{ fontSize: 11 }} /><Tooltip contentStyle={tipStyle} /><Bar dataKey="bookings" fill="#0f9f92" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer>; }
