import { cva } from 'class-variance-authority';
import { AlertCircle, CheckCircle2, Info, X } from 'lucide-react';
import { createContext, useCallback, useContext, useState } from 'react';
import { cn } from '../lib/utils';

const buttonVariants = cva('inline-flex items-center justify-center gap-2 rounded-lg text-sm font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-ring disabled:pointer-events-none disabled:opacity-50', { variants: { variant: { default: 'bg-primary text-primary-foreground hover:bg-primary/90', outline: 'border bg-card hover:bg-muted', ghost: 'hover:bg-muted', destructive: 'bg-red-600 text-white hover:bg-red-700' }, size: { default: 'h-10 px-4', sm: 'h-8 px-3 text-xs', icon: 'h-10 w-10' } }, defaultVariants: { variant: 'default', size: 'default' } });
export function Button({ className, variant, size, ...props }) { return <button className={cn(buttonVariants({ variant, size }), className)} {...props} />; }
export function Input({ className, ...props }) { return <input className={cn('h-10 w-full rounded-lg border bg-transparent px-3 text-sm outline-none placeholder:text-muted-foreground focus:ring-2 focus:ring-ring', className)} {...props} />; }
export function Select({ className, children, ...props }) { return <select className={cn('h-10 w-full rounded-lg border bg-card px-3 text-sm outline-none focus:ring-2 focus:ring-ring', className)} {...props}>{children}</select>; }
export function Card({ className, children }) { return <section className={cn('rounded-xl border bg-card text-card-foreground shadow-panel', className)}>{children}</section>; }
export function CardHeader({ className, children }) { return <div className={cn('flex items-center justify-between px-5 pt-5', className)}>{children}</div>; }
export function CardContent({ className, children }) { return <div className={cn('p-5', className)}>{children}</div>; }
export function Spinner({ className }) { return <span className={cn('inline-block h-5 w-5 animate-spin rounded-full border-2 border-current border-t-transparent', className)} />; }
export function PageState({ type = 'loading', message }) { const content = type === 'loading' ? <><Spinner /><span>Loading data…</span></> : type === 'error' ? <><AlertCircle className="text-red-500" /><span>{message || 'Something went wrong.'}</span></> : <><Info /><span>{message || 'No records found.'}</span></>; return <Card className="flex min-h-48 items-center justify-center gap-3 p-6 text-muted-foreground">{content}</Card>; }
export function StatusBadge({ status }) { const colors = { pending: 'bg-amber-100 text-amber-800 dark:bg-amber-500/15 dark:text-amber-300', assigned: 'bg-sky-100 text-sky-800 dark:bg-sky-500/15 dark:text-sky-300', mechanic_on_the_way: 'bg-violet-100 text-violet-800 dark:bg-violet-500/15 dark:text-violet-300', in_progress: 'bg-blue-100 text-blue-800 dark:bg-blue-500/15 dark:text-blue-300', completed: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-500/15 dark:text-emerald-300', cancelled: 'bg-red-100 text-red-800 dark:bg-red-500/15 dark:text-red-300', available: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-500/15 dark:text-emerald-300', busy: 'bg-orange-100 text-orange-800 dark:bg-orange-500/15 dark:text-orange-300', offline: 'bg-slate-200 text-slate-700 dark:bg-slate-500/20 dark:text-slate-300' }; return <span className={cn('inline-flex rounded-full px-2.5 py-1 text-xs font-semibold', colors[status] || 'bg-muted text-muted-foreground')}>{String(status || '').replaceAll('_', ' ')}</span>; }
export function PageHeader({ title, description, children }) { return <div className="mb-6 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-bold tracking-tight">{title}</h2>{description && <p className="mt-1 text-sm text-muted-foreground">{description}</p>}</div>{children}</div>; }
export function Pagination({ pagination = {}, onPage }) { const { page = 1, totalPages = 1, total = 0 } = pagination; return <div className="flex items-center justify-between border-t px-4 py-3 text-sm"><span className="text-muted-foreground">{total} records · Page {page} of {Math.max(totalPages, 1)}</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={page <= 1} onClick={() => onPage(page - 1)}>Previous</Button><Button variant="outline" size="sm" disabled={page >= totalPages} onClick={() => onPage(page + 1)}>Next</Button></div></div>; }
export function Avatar({ name = '', src, className }) { return src ? <img src={src} alt="" className={cn('h-10 w-10 rounded-full object-cover', className)} /> : <span className={cn('grid h-10 w-10 shrink-0 place-items-center rounded-full bg-primary/10 font-semibold text-primary', className)}>{name.split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase()}</span>; }

const ToastContext = createContext(null);
export function ToastProvider({ children }) { const [toasts, setToasts] = useState([]); const toast = useCallback((message, type = 'success') => { const id = Date.now() + Math.random(); setToasts((items) => [...items, { id, message, type }]); setTimeout(() => setToasts((items) => items.filter((item) => item.id !== id)), 4200); }, []); return <ToastContext.Provider value={toast}>{children}<div className="fixed right-4 top-4 z-50 space-y-2">{toasts.map((item) => <div key={item.id} className={cn('flex max-w-sm items-center gap-3 rounded-xl border bg-card p-3 shadow-lg', item.type === 'error' && 'border-red-300')}><>{item.type === 'error' ? <AlertCircle className="h-5 text-red-500" /> : <CheckCircle2 className="h-5 text-emerald-500" />}</><p className="text-sm">{item.message}</p><button onClick={() => setToasts((items) => items.filter((toastItem) => toastItem.id !== item.id))}><X className="h-4" /></button></div>)}</div></ToastContext.Provider>; }
export const useToast = () => useContext(ToastContext);
