import { BarChart3, CarFront, ClipboardList, LogOut, Menu, Moon, Sun, Users, Wrench } from 'lucide-react';
import { NavLink, Outlet, useLocation } from 'react-router-dom';
import { useState } from 'react';
import NotificationPanel from '../components/NotificationPanel';
import { Button } from '../components/ui';
import { useAuth } from '../context/AuthContext';
import { useTheme } from '../context/ThemeContext';
import { useSocket } from '../hooks/useSocket';
import { cn } from '../lib/utils';

const navigation = [{ to: '/dashboard', label: 'Dashboard', icon: BarChart3 }, { to: '/bookings', label: 'Bookings', icon: ClipboardList }, { to: '/mechanics', label: 'Mechanics', icon: Wrench }, { to: '/customers', label: 'Customers', icon: Users }, { to: '/analytics', label: 'Analytics', icon: BarChart3 }];
const pageTitles = { dashboard: 'Operations overview', bookings: 'Bookings', mechanics: 'Mechanics', customers: 'Customers', analytics: 'Analytics' };
export default function AppLayout() { const [mobileOpen, setMobileOpen] = useState(false); const { user, logout } = useAuth(); const { theme, toggleTheme } = useTheme(); const location = useLocation(); useSocket(); const key = location.pathname.split('/')[1]; const sidebar = <aside className="flex h-full w-64 flex-col border-r bg-card p-4"><NavLink to="/dashboard" className="mb-8 flex items-center gap-3 px-2 text-lg font-bold"><span className="grid h-9 w-9 place-items-center rounded-lg bg-primary text-primary-foreground"><CarFront className="h-5" /></span>Instant Mechanic</NavLink><nav className="space-y-1">{navigation.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} onClick={() => setMobileOpen(false)} className={({ isActive }) => cn('flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-muted-foreground hover:bg-muted hover:text-foreground', isActive && 'bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground')}><Icon className="h-4 w-4" />{label}</NavLink>)}</nav><div className="mt-auto rounded-lg bg-muted p-3 text-xs text-muted-foreground">Live operations workspace</div></aside>; return <div className="min-h-screen"><div className="hidden lg:fixed lg:inset-y-0 lg:flex">{sidebar}</div>{mobileOpen && <div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-black/40" onClick={() => setMobileOpen(false)} aria-label="Close menu" /><div className="relative h-full">{sidebar}</div></div>}<main className="lg:pl-64"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b bg-background/90 px-4 backdrop-blur lg:px-8"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setMobileOpen(true)}><Menu className="h-5" /></Button><div><h1 className="font-semibold">{pageTitles[key] || 'Operations'}</h1><p className="hidden text-xs text-muted-foreground sm:block">Instant Mechanic live service management</p></div></div><div className="flex items-center gap-1"><Button variant="ghost" size="icon" onClick={toggleTheme} aria-label="Toggle dark mode">{theme === 'dark' ? <Sun className="h-5" /> : <Moon className="h-5" />}</Button><NotificationPanel /><div className="hidden border-l pl-3 text-right sm:block"><p className="text-sm font-medium">{user?.name}</p><p className="text-xs text-muted-foreground">{user?.role}</p></div><Button variant="ghost" size="icon" onClick={logout} aria-label="Log out"><LogOut className="h-5" /></Button></div></header><div className="p-4 lg:p-8"><Outlet /></div></main></div>; }
